# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56f7f17b36a301821ef1b279110e5640e96f55ba3276c7839ee024281e8827d21addd0d6b8be7b0a2c2f30074912bd3a5a244e4c49127f5252809e0fdf62d54c

test:
  secret_key_base: 6781622043ba90fad1ff9d10677d74dcdf47d2df7364585cf0c3eaff78f675055851af70aab42c2497ea4e55535af7662b2f2cbcb3e717f99abd71530d98cadf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
